### ISSUE TITLE
installing PotreeConverter on Ubuntu 18.04

### ISSUE THREAD

**Issue by cgonzalezdai** [potree/PotreeConverter#509]
I am installing PotreeConverter on Ubuntu 18.04 and face the following error while running make from build directory.

`[ 64%] Linking CXX executable PotreeConverter
CMakeFiles/PotreeConverter.dir/Converter/src/chunker_countsort_laszip.cpp.o: In function 'std::result_of<std::integral_constant<bool, false> ()>::type __pstl::__internal::__except_handler<__pstl::__internal::__pattern_walk1<__pstl::execution::v1::parallel_policy&, __gnu_cxx::__normal_iterator<Source*, std::vector<Source, std::allocator<Source> > >, computeOutputAttributes(std::vector<Source, std::allocator<Source> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)::{lambda(Source)#1}, std::integral_constant<bool, false> >(__pstl::execution::v1::parallel_policy&, __gnu_cxx::__normal_iterator<Source*, std::vector<Source, std::allocator<Source> > >, __pstl::execution::v1::parallel_policy&, computeOutputAttributes(std::vector<Source, std::allocator<Source> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)::{lambda(Source)#1}, std::integral_constant<bool, false>, computeOutputAttributes(std::vector<Source, std::allocator<Source> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)::{lambda(Source)#1}<bool, true>)::{lambda()#1}>(std::integral_constant<bool, false>)':
chunker_countsort_laszip.cpp:(.text._ZN6__pstl10__internal16__except_handlerIZNS0_15__pattern_walk1IRNS_9execution2v115parallel_policyEN9__gnu_cxx17__normal_iteratorIP6SourceSt6vectorIS9_SaIS9_EEEEZ23computeOutputAttributesRSD_SB_INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISL_EEEUlS9_E_St17integral_constantIbLb0EEEEvOT_T0_ST_T1_T2_SP_IbLb1EEEUlvE_EENSt9result_ofIFSR_vEE4typeESR_[_ZN6__pstl10__internal16__except_handlerIZNS0_15__pattern_walk1IRNS_9execution2v115parallel_policyEN9__gnu_cxx17__normal_iteratorIP6SourceSt6vectorIS9_SaIS9_EEEEZ23computeOutputAttributesRSD_SB_INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISL_EEEUlS9_E_St17integral_constantIbLb0EEEEvOT_T0_ST_T1_T2_SP_IbLb1EEEUlvE_EENSt9result_ofIFSR_vEE4typeESR_]+0x218): undefined reference to 'tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
CMakeFiles/PotreeConverter.dir/Converter/src/main.cpp.o: In function 'curateSources(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
main.cpp:(.text+0x9f48): undefined reference to 'tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
CMakeFiles/PotreeConverter.dir/Converter/src/main.cpp.o: In function 'std::enable_if<__pstl::execution::v1::is_execution_policy<std::remove_cv<std::remove_reference<__pstl::execution::v1::parallel_unsequenced_policy&>::type>::type>::value, void>::type std::sort<__pstl::execution::v1::parallel_unsequenced_policy&, __gnu_cxx::__normal_iterator<SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point*, std::vector<SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, std::allocator<SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point> > >, SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::{lambda(Node*)#2}::operator()(Node*) const::{lambda(SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point)#3}>(std::remove_cv&&, __gnu_cxx::__normal_iterator<SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point*, std::vector<SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, std::allocator<SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point> > >, std::enable_if<__pstl::execution::v1::is_execution_policy<std::remove_cv<std::remove_reference<__pstl::execution::v1::parallel_unsequenced_policy&>::type>::type>::value, void>::type, SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::{lambda(Node*)#2}::operator()(Node*) const::{lambda(SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, SamplerPoisson::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point)#3})':
main.cpp:(.text._ZSt4sortIRN6__pstl9execution2v127parallel_unsequenced_policyEN9__gnu_cxx17__normal_iteratorIPZN14SamplerPoisson6sampleESt10shared_ptrI4NodeE10AttributesdSt8functionIFvPS9_EEE5PointSt6vectorISG_SaISG_EEEEZZNS7_6sampleESA_SB_dSF_ENKUlSD_E0_clESD_EUlSG_SG_E1_ENSt9enable_ifIXsrNS2_19is_execution_policyINSt9remove_cvINSt16remove_referenceIT_E4typeEE4typeEEE5valueEvE4typeEOSS_T0_S11_T1_[_ZSt4sortIRN6__pstl9execution2v127parallel_unsequenced_policyEN9__gnu_cxx17__normal_iteratorIPZN14SamplerPoisson6sampleESt10shared_ptrI4NodeE10AttributesdSt8functionIFvPS9_EEE5PointSt6vectorISG_SaISG_EEEEZZNS7_6sampleESA_SB_dSF_ENKUlSD_E0_clESD_EUlSG_SG_E1_ENSt9enable_ifIXsrNS2_19is_execution_policyINSt9remove_cvINSt16remove_referenceIT_E4typeEE4typeEEE5valueEvE4typeEOSS_T0_S11_T1_]+0x77): undefined reference to 'tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
CMakeFiles/PotreeConverter.dir/Converter/src/main.cpp.o: In function 'std::enable_if<__pstl::execution::v1::is_execution_policy<std::remove_cv<std::remove_reference<__pstl::execution::v1::parallel_unsequenced_policy&>::type>::type>::value, void>::type std::sort<__pstl::execution::v1::parallel_unsequenced_policy&, __gnu_cxx::__normal_iterator<SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point*, std::vector<SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, std::allocator<SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point> > >, SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::{lambda(Node*)#2}::operator()(Node*) const::{lambda(SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point)#3}>(std::remove_cv&&, __gnu_cxx::__normal_iterator<SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point*, std::vector<SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, std::allocator<SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point> > >, std::enable_if<__pstl::execution::v1::is_execution_policy<std::remove_cv<std::remove_reference<__pstl::execution::v1::parallel_unsequenced_policy&>::type>::type>::value, void>::type, SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::{lambda(Node*)#2}::operator()(Node*) const::{lambda(SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point, SamplerPoissonAverage::sample(std::shared_ptr<Node>, Attributes, double, std::function<void (Node*)>)::Point)#3})':
main.cpp:(.text._ZSt4sortIRN6__pstl9execution2v127parallel_unsequenced_policyEN9__gnu_cxx17__normal_iteratorIPZN21SamplerPoissonAverage6sampleESt10shared_ptrI4NodeE10AttributesdSt8functionIFvPS9_EEE5PointSt6vectorISG_SaISG_EEEEZZNS7_6sampleESA_SB_dSF_ENKUlSD_E0_clESD_EUlSG_SG_E1_ENSt9enable_ifIXsrNS2_19is_execution_policyINSt9remove_cvINSt16remove_referenceIT_E4typeEE4typeEEE5valueEvE4typeEOSS_T0_S11_T1_[_ZSt4sortIRN6__pstl9execution2v127parallel_unsequenced_policyEN9__gnu_cxx17__normal_iteratorIPZN21SamplerPoissonAverage6sampleESt10shared_ptrI4NodeE10AttributesdSt8functionIFvPS9_EEE5PointSt6vectorISG_SaISG_EEEEZZNS7_6sampleESA_SB_dSF_ENKUlSD_E0_clESD_EUlSG_SG_E1_ENSt9enable_ifIXsrNS2_19is_execution_policyINSt9remove_cvINSt16remove_referenceIT_E4typeEE4typeEEE5valueEvE4typeEOSS_T0_S11_T1_]+0x85): undefined reference to 'tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
collect2: error: ld returned 1 exit status
CMakeFiles/PotreeConverter.dir/build.make:180: recipe for target 'PotreeConverter' failed
make[2]: *** [PotreeConverter] Error 1
CMakeFiles/Makefile2:160: recipe for target 'CMakeFiles/PotreeConverter.dir/all' failed
make[1]: *** [CMakeFiles/PotreeConverter.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by midnight-dev** [comment]
I'm not sure that's the correct TBB you need to use. The one that works for me was in the official Ubuntu apt repo. It was something like `tbb-dev`, so I'd recommend using a terminal command like `sudo apt-get install tbb` and hitting tab a few times to list the available packages. Install it that way to make sure you're getting what the project expects to have when it needs to compile.

**Comment by cgonzalezdai** [comment]
@midnight-dev Thanks for the help. Your comment guided me to find the problem.

**Comment by BerlinDorin** [comment]
> @midnight-dev Thanks for the help. Your comment guided me to find the problem.

could you tell me how you install “tbb” i found the same problem

**Comment by cgonzalezdai** [comment]
@BerlinDorin My script should work fine on a clean install of ubuntu 18.04
The tbb error, in my case, was conditioned by previous failed attempts.
This worked for me: 
`$ apt-get removes libtbb-dev `

**Comment by khanashes** [comment]
After this step
`sudo cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=/pathtofolder/LAStools/LASzip/dll -DLASZIP_LIBRARY=/pathtofolder/LAStools/LASzip/build/src/liblaszip.so ..`
Try this
`cd ..`
`make`

**Comment by geotyr** [comment]
so...I am working on a linuxmint 21.3 Virginia (package base ubuntu Jammy)
instructions for installing PotreeConverter 2.1 would be

### **STEP1: prerequirements**

install cmake (must be 3.16 o higher version)
`sudo apt-get install cmake`
install build-essential
`sudo apt-get install build-essential`
install libtbb-dev
`sudo apt-get install libtbb-dev`
(there might be more g++, gcc, make?? I am not sure, they were already installed on my machine)

### **STEP2: download source files**
(source code not the compiled one, I did not managed to use the compiled one)
https://github.com/potree/PotreeConverter/archive/refs/tags/2.1.1.tar.gz

### **STEP3: build**
unzip
create the build directory
`mkdir build`
enter the build directory
`cd build`
run cmake
`cmake ..`
you will have some comments about test files that are not found because they are not provided in the dowload
THEN run make
`make`
it takes a while and you need to reach the 100% of the build
[100%] Built target brotli

### **STEP4: run PotreeConverter from the build folder**
`./PotreeConverter <input_file> -o <output_directory>`

the inputfile must be a .las file that you can create with cloudcompare, sadly .ply files are not supported anymore https://github.com/potree/PotreeConverter/issues/519

it is a bit hard to understand why for an open project windows instructions are more detailed than linux ones
I hope this will help new linux installs for "newbies" like me

**Comment by chogerlate** [comment]
> so...I am working on a linuxmint 21.3 Virginia (package base ubuntu Jammy) instructions for installing PotreeConverter 2.1 would be
> ### **STEP1: prerequirements**
> 
> install cmake (must be 3.16 o higher version) `sudo apt-get install cmake` install build-essential `sudo apt-get install build-essential` install libtbb-dev `sudo apt-get install libtbb-dev` (there might be more g++, gcc, make?? I am not sure, they were already installed on my machine)
> ### **STEP2: download source files**
> 
> (source code not the compiled one, I did not managed to use the compiled one) https://github.com/potree/PotreeConverter/archive/refs/tags/2.1.1.tar.gz
> ### **STEP3: build**
> 
> unzip create the build directory `mkdir build` enter the build directory `cd build` run cmake `cmake ..` you will have some comments about test files that are not found because they are not provided in the dowload THEN run make `make` it takes a while and you need to reach the 100% of the build [100%] Built target brotli
> ### **STEP4: run PotreeConverter from the build folder**
> 
> `./PotreeConverter <input_file> -o <output_directory>`
> 
> the inputfile must be a .las file that you can create with cloudcompare, sadly .ply files are not supported anymore #519
> 
> it is a bit hard to understand why for an open project windows instructions are more detailed than linux ones I hope this will help new linux installs for "newbies" like me

This work like charm thx
