### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by m-schuetz**

### CODE REVIEW

**Comment by perhallstroem** [comment]
@m-schuetz After this, I can no longer get it to build on Ubuntu. It fails like this:

```
/build/PotreeConverter/PotreeConverter/src/stuff.cpp:38:21: warning: extra tokens at end of #include directive
 #include <Windows.h>>
                     ^
/build/PotreeConverter/PotreeConverter/src/stuff.cpp:38:22: fatal error: Windows.h: No such file or directory
compilation terminated.
```

From my limited understanding this problem would have been introduced in commit b74f2cafa4b728cc2e28c7b2f8dc3a6731be223c. I have very limited recent experience of building C/C++ applications and have never used Boost, so I'm not really sure why it is not working. That `BOOST_OS_WINDOWS` is defined when compiling on Ubuntu is a bit surprising.

**Comment by m-schuetz** [comment]
Does it work if you remove the second ">" ? I don't think that should be there.

**Comment by perhallstroem** [comment]
Hi @m-schuetz, sorry for the delay. The stray ">" doesn't seem to bother it too much: if removed the warning goes away but the error remains (can't find **Windows.h**). I presume it has something to do with the OS detection not working as it should. Not knowing Boost, I have no idea where those would be defined.

**Comment by m-schuetz** [comment]
Discussion continued in #228
