### ISSUE TITLE
Build error on debian 9

### ISSUE THREAD

**Issue by tteke** [potree/PotreeConverter#382]
I have debian 9.0, gcc 6.3.0 and I get the error below after make command 

`[  8%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PotreeWriter.cpp.o
/home/tteke/Downloads/potreeconverter/master/PotreeConverter/src/PotreeWriter.cpp: In lambda function:
/home/tteke/Downloads/potreeconverter/master/PotreeConverter/src/PotreeWriter.cpp:298:36: error: invalid initialization of non-const reference of type ‘Potree::Point&’ from an rvalue of type ‘Potree::Point’
      writer->write(reader->getPoint());
                    ~~~~~~~~~~~~~~~~^~`

**Comment by omaralvarez** [comment]
I have the same problem compiling on Ubuntu 18.04 x64.

**Comment by omaralvarez** [comment]
Solved it creating a temporal variable:

```cpp
Potree::Point point = reader->getPoint();
writer->write(point);
```

**Comment by geotyr** [comment]
I have the same issue
@omaralvarez 
> Potree::Point point = reader->getPoint();
writer->write(point);
could you tell where and how did you create the temporal variable? I am not sure how to use your comment
thank you

**Comment by kpj** [comment]
@geotyr: in `PotreeConverter/PotreeConverter/src/PotreeWriter.cpp` you need to replace the line 298 (as of commit 08b83dd292d8ac98cb0f83be44a0cc5b03261aca)
```
writer->write(reader->getPoint());
```
with
```
Potree::Point point = reader->getPoint();
writer->write(point);
```

**Comment by geotyr** [comment]
@kpj thank you, that part worked

I've had another error afterwards
`/home/geotyr/PROGRAMMES/PotreeConverter/PotreeConverter/src/main.cpp:14:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
`
that I solved thanks to this post https://stackoverflow.com/questions/39231363/fatal-error-filesystem-no-such-file-or-directory/39231488
which says to change in the main.cpp file the 
`#include <filesystem>` 
with 
`#include <experimental/filesystem> `
for gcc version prior to 8.

running my first conversions, thanks to all :)

**Comment by Tarot67** [comment]
Yes it's work! Thank!

**Comment by potree** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. 

At the moment, there are only windows builds available but linux builds are on the roadmap.

**Comment by syonfox** [comment]
Well ill just leave this here worked on debian testing and ubuntu 20.04 as I had some issues still with the outputs of converter2.0 while this worked reliably.
```
#!/bin/sh

REL_PATH='../'
WORKING_DIR='pointcloud_tools'

echo ===========================================
echo Installing Potree Converter 1.7
echo Working In Directory: $REL_PATH$WORKING_DIR
echo ===========================================

cd $REL_PATH
mkdir $WORKING_DIR
cd $WORKING_DIR
dir
echo ===========================================
echo installing dependancys
echo ===========================================
sudo apt update
sudo apt install git cmake build-essential
echo ===========================================
echo CLONING LASTools
echo ===========================================
git clone https://github.com/m-schuetz/LAStools.git
cd LAStools
LASToolsPath=`pwd`
cd LASzip
cmake .
## this is in the potree readme but not the lastools one
#mkdir build
#cd build
#cmake -DCMAKE_BUILD_TYPE=Release ..
make

cd ../..
echo ===========================================
echo DONE BUILDING LASTools
echo CLONING potreeConverter1.7
echo ===========================================
git clone https://github.com/potree/PotreeConverter.git -b 1.7PRE
cd PotreeConverter
#usualy errors without this hot fix
# see https://github.com/potree/PotreeConverter/issues/382
sed -i -e 's/writer->write(reader->getPoint());/Potree::Point point = reader->getPoint();\n\t\t\t\t\twriter->write(point);/g' PotreeConverter/src/PotreeWriter.cpp
mkdir build
cd build
#cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=/home/kier/pointcloud_tools/LAStools/LASzip/dll -DLASZIP_LIBRARY=/home/kier/pointcloud_tools/LAStools/LASzip/build/src/liblaszip.so ..
cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=$LASToolsPath/LASzip/dll -DLASZIP_LIBRARY=$LASToolsPath/LASzip/src/liblaszip.so ..
make

echo ===========================================
echo DONE BUILDING Potree Converter
echo Copying Binary to /usr/local/bin this requires sudo
echo ===========================================
sudo cp PotreeConverter/PotreeConverter /usr/local/bin/PotreeConverter1.7
echo ===========================================
echo TESTING CONVERTER IF THIS DOSENT OUTPUT HELP LOOK FOR ERRORS OR RED
echo ===========================================
PotreeConverter1.7
cd ..
```
