### ISSUE TITLE
Build Issue on Mac OSX 

### ISSUE THREAD

**Issue by stephenpardy** [potree/PotreeConverter#30]
I am getting an error while trying to build on Mac OSX 10.9:

 Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PotreeConverter.cpp.o
In file included from ~/Code/PotreeConverter/PotreeConverter/src/PotreeConverter.cpp:13:
~/Code/PotreeConverter/PotreeConverter/include/PlyPointReader.h:235:18: error: non-const lvalue reference to type 'Vector3<[...]>' cannot bind to a temporary of type 'Vector3<[...]>
aabb->update(p.position());
