### ISSUE TITLE
Does not build on macos

### ISSUE THREAD

**Issue by themightyoarfish** [potree/PotreeConverter#599]
This project does not build on macos 12.5.1 on M1:

```
[  9%] Built target brotlicommon-static
[ 46%] Built target laszip
[ 54%] Built target brotlidec-static
[ 88%] Built target brotlienc-static
Consolidate compiler generated dependencies of target PotreeConverter
[ 93%] Building CXX object CMakeFiles/PotreeConverter.dir/Converter/src/indexer.cpp.o
[ 93%] Building CXX object CMakeFiles/PotreeConverter.dir/Converter/src/chunker_countsort_laszip.cpp.o
[ 93%] Building CXX object CMakeFiles/PotreeConverter.dir/Converter/src/main.cpp.o
[ 95%] Building CXX object CMakeFiles/PotreeConverter.dir/Converter/modules/unsuck/unsuck_platform_specific.cpp.o
[ 96%] Building CXX object CMakeFiles/PotreeConverter.dir/Converter/modules/LasLoader/LasLoader.cpp.o
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/modules/unsuck/unsuck_platform_specific.cpp:2:
/Users/rasmus/Downloads/PotreeConverter/Converter/modules/unsuck/unsuck.hpp:435:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/Converter/modules/unsuck/unsuck.hpp:444:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/Converter/modules/unsuck/unsuck.hpp:462:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/Converter/modules/unsuck/unsuck.hpp:466:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
4 errors generated.
make[3]: *** [CMakeFiles/PotreeConverter.dir/Converter/modules/unsuck/unsuck_platform_specific.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/modules/LasLoader/LasLoader.cpp:2:
In file included from /Users/rasmus/Downloads/PotreeConverter/./Converter/modules/LasLoader/LasLoader.h:4:
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:435:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:444:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:462:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:466:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
4 errors generated.
make[3]: *** [CMakeFiles/PotreeConverter.dir/Converter/modules/LasLoader/LasLoader.cpp.o] Error 1
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:6:
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:435:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:444:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:462:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:466:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:9:
In file included from /Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:8:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/PotreeConverter.h:210:24: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
                auto parallel = std::execution::par;
                                ~~~~~^~~~~~~~~
                                     exception
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/exception:99:29: note: 'exception' declared here
class _LIBCPP_EXCEPTION_ABI exception
                            ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:9:
In file included from /Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:8:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/PotreeConverter.h:210:35: error: no member named 'par' in 'std::exception'
                auto parallel = std::execution::par;
                                ~~~~~~~~~~~~~~~~^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:9:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:103:31: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') in initializer list [-Wc++11-narrowing]
                                        Point point = { x, y, z, i, childIndex };
                                                                 ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:103:31: note: insert an explicit cast to silence this issue
                                        Point point = { x, y, z, i, childIndex };
                                                                 ^
                                                                 static_cast<int32_t>( )
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:103:34: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') in initializer list [-Wc++11-narrowing]
                                        Point point = { x, y, z, i, childIndex };
                                                                    ^~~~~~~~~~
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:103:34: note: insert an explicit cast to silence this issue
                                        Point point = { x, y, z, i, childIndex };
                                                                    ^~~~~~~~~~
                                                                    static_cast<int32_t>( )
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:182:25: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
                        auto parallel = std::execution::par_unseq;
                                        ~~~~~^~~~~~~~~
                                             exception
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/exception:99:29: note: 'exception' declared here
class _LIBCPP_EXCEPTION_ABI exception
                            ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:9:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson.h:182:36: error: no member named 'par_unseq' in 'std::exception'
                        auto parallel = std::execution::par_unseq;
                                        ~~~~~~~~~~~~~~~~^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:10:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson_average.h:283:25: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
                        auto parallel = std::execution::par_unseq;
                                        ~~~~~^~~~~~~~~
                                             exception
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/exception:99:29: note: 'exception' declared here
class _LIBCPP_EXCEPTION_ABI exception
                            ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:10:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/sampler_poisson_average.h:283:36: error: no member named 'par_unseq' in 'std::exception'
                        auto parallel = std::execution::par_unseq;
                                        ~~~~~~~~~~~~~~~~^
/Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:183:23: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
        auto parallel = std::execution::par;
                        ~~~~~^~~~~~~~~
                             exception
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/exception:99:29: note: 'exception' declared here
class _LIBCPP_EXCEPTION_ABI exception
                            ^
/Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:183:34: error: no member named 'par' in 'std::exception'
        auto parallel = std::execution::par;
                        ~~~~~~~~~~~~~~~~^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/main.cpp:495:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/HierarchyBuilder.h:326:27: warning: equality comparison result unused [-Wunused-comparison]
                                root_batch_node->type == TYPE::LEAF;
                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/HierarchyBuilder.h:326:27: note: use '=' to turn this equality comparison into an assignment
                                root_batch_node->type == TYPE::LEAF;
                                                      ^~
                                                      =
1 warning and 14 errors generated.
make[3]: *** [CMakeFiles/PotreeConverter.dir/Converter/src/main.cpp.o] Error 1
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/chunker_countsort_laszip.cpp:10:
In file included from /Users/rasmus/Downloads/PotreeConverter/./Converter/include/chunker_countsort_laszip.h:8:
In file included from /Users/rasmus/Downloads/PotreeConverter/./Converter/include/Attributes.h:10:
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:435:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:444:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:462:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:466:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/chunker_countsort_laszip.cpp:22:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/PotreeConverter.h:210:24: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
                auto parallel = std::execution::par;
                                ~~~~~^~~~~~~~~
                                     exception
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/exception:99:29: note: 'exception' declared here
class _LIBCPP_EXCEPTION_ABI exception
                            ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/chunker_countsort_laszip.cpp:22:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/PotreeConverter.h:210:35: error: no member named 'par' in 'std::exception'
                auto parallel = std::execution::par;
                                ~~~~~~~~~~~~~~~~^
6 errors generated.
make[3]: *** [CMakeFiles/PotreeConverter.dir/Converter/src/chunker_countsort_laszip.cpp.o] Error 1
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/indexer.cpp:6:
In file included from /Users/rasmus/Downloads/PotreeConverter/./Converter/include/indexer.h:21:
In file included from /Users/rasmus/Downloads/PotreeConverter/./Converter/include/Attributes.h:10:
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:435:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:444:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:462:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
/Users/rasmus/Downloads/PotreeConverter/./Converter/modules/unsuck/unsuck.hpp:466:3: error: use of undeclared identifier 'fseek_64_all_platforms'
                fseek_64_all_platforms(file, start, SEEK_SET);
                ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/indexer.cpp:10:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/PotreeConverter.h:210:24: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
                auto parallel = std::execution::par;
                                ~~~~~^~~~~~~~~
                                     exception
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/exception:99:29: note: 'exception' declared here
class _LIBCPP_EXCEPTION_ABI exception
                            ^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/indexer.cpp:10:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/PotreeConverter.h:210:35: error: no member named 'par' in 'std::exception'
                auto parallel = std::execution::par;
                                ~~~~~~~~~~~~~~~~^
In file included from /Users/rasmus/Downloads/PotreeConverter/Converter/src/indexer.cpp:13:
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/HierarchyBuilder.h:326:27: warning: equality comparison result unused [-Wunused-comparison]
                                root_batch_node->type == TYPE::LEAF;
                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/Users/rasmus/Downloads/PotreeConverter/./Converter/include/HierarchyBuilder.h:326:27: note: use '=' to turn this equality comparison into an assignment
                                root_batch_node->type == TYPE::LEAF;
                                                      ^~
                                                      =
/Users/rasmus/Downloads/PotreeConverter/Converter/src/indexer.cpp:1165:12: warning: implicit conversion from 'std::numeric_limits<long long>::type' (aka 'long long') to 'int32_t' (aka 'int') changes value from 9223372036854775807 to -1 [-Wconstant-conversion]
                        min.x = std::numeric_limits<int64_t>::max();
                              ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rasmus/Downloads/PotreeConverter/Converter/src/indexer.cpp:1166:12: warning: implicit conversion from 'std::numeric_limits<long long>::type' (aka 'long long') to 'int32_t' (aka 'int') changes value from 9223372036854775807 to -1 [-Wconstant-conversion]
                        min.y = std::numeric_limits<int64_t>::max();
                              ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rasmus/Downloads/PotreeConverter/Converter/src/indexer.cpp:1167:12: warning: implicit conversion from 'std::numeric_limits<long long>::type' (aka 'long long') to 'int32_t' (aka 'int') changes value from 9223372036854775807 to -1 [-Wconstant-conversion]
                        min.z = std::numeric_limits<int64_t>::max();
                              ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings and 6 errors generated.
make[3]: *** [CMakeFiles/PotreeConverter.dir/Converter/src/indexer.cpp.o] Error 1
make[2]: *** [CMakeFiles/PotreeConverter.dir/all] Error 2
make[1]: *** [CMakeFiles/PotreeConverter.dir/rule] Error 2
make: *** [PotreeConverter] Error 2
```

compiler:

Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0

**Comment by m-schuetz** [comment]
Two problems here: 
* Mac compilers tend to be always behind and lack std features.
* I don't have time&resources to maintain a mac build

Pull Requests that provide Mac support without compromising windows&linux support are welcome, however.

**Comment by m-schuetz** [comment]
You could try this PR, though: https://github.com/potree/PotreeConverter/pull/568

It's mainly not merged because too many files are affected & bigger changes to the PotreeConverter are on the horizon.

**Comment by themightyoarfish** [comment]
Yeah, I've found a fork. It would be useful to note the supported OSes in the readme.

**Comment by zjyhjqs** [comment]
> Mac compilers tend to be always behind and lack std features.

This issue is caused by libc++ (same problem on Android). I've enabled `-fexperimental-library` for it in my PR #686.

**Comment by 1xtr** [comment]
> > Mac compilers tend to be always behind and lack std features.
> 
> This issue is caused by libc++ (same problem on Android). I've enabled `-fexperimental-library` for it in my PR [#686](https://github.com/potree/PotreeConverter/pull/686).

@zjyhjqs I create a fork and merge your PR
But have new error, can you help me?
```cli
make
[  6%] Built target brotlicommon-static
[ 28%] Built target brotlienc-static
[ 52%] Built target laszip
[ 57%] Built target brotlidec-static
[ 58%] Linking CXX executable PotreeConverter
ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc++experimental.a[arm64][3](libdispatch.cpp.o)) was built for newer 'macOS' version (15.5) than being linked (15.0)
Undefined symbols for architecture arm64:
  "getCpuData()", referenced from:
      __GLOBAL__sub_I_chunker_countsort_laszip.cpp in chunker_countsort_laszip.cpp.o
      __GLOBAL__sub_I_chunker_countsort_laszip.cpp in chunker_countsort_laszip.cpp.o
      indexer::doIndexing(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, State&, Options&, Sampler&) in indexer.cpp.o
      _main in main.cpp.o
      Monitor::_print() in main.cpp.o
  "getMemoryData()", referenced from:
      Buffer::Buffer(long long) in chunker_countsort_laszip.cpp.o
      indexer::Indexer::waitUntilMemoryBelow(int) in indexer.cpp.o
      indexer::Indexer::waitUntilMemoryBelow(int) in indexer.cpp.o
      Monitor::_print() in main.cpp.o
  "launchMemoryChecker(long long, double)", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [PotreeConverter] Error 1
make[1]: *** [CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by zjyhjqs** [comment]
> [@zjyhjqs](https://github.com/zjyhjqs) I create a fork and merge your PR But have new error, can you help me?

As noted in `TODO`, hardware statistics for macOS (e.g. `getCpuData`) has not been implemented in my PR yet.

The related modifications have been done in #568 and #662 , so originally I don't want to duplicate their works. (But rebasing them onto my PR seems hard. I'm considering to solve it in my PR.)

You could try apply this patch on my PR. I've not pushed on my branch because it's not tested yet. [unsuck-macos.patch](https://github.com/user-attachments/files/22975784/unsuck-macos.patch)

**Comment by zjyhjqs** [comment]
> @zjyhjqs I create a fork and merge your PR

My PR is updated. I've tested on Mac mini M4 and it works fine.
